"""
Generated by Wolf DSL Translator
Game: SimpleGame
"""

import random
import time
from pathlib import Path
from typing import List, Dict, Optional

# Engine Imports
from game.engine import Game, GamePhase, GameStep, GameAction
from game.models import Role, DeathReason
from game.player import Player


# ==========================================
# Action Classes
# ==========================================

# ==========================================
# Main Game Class
# ==========================================

class SimpleGame(Game):
    """SimpleGame implementation generated from DSL."""

    def __init__(self, players: List[Dict[str, str]], event_emitter=None, input_handler=None):
        super().__init__("SimpleGame", players, event_emitter, input_handler)

        # DSL Global Variables
        self.score = 100

        self._init_phases()

    def _init_phases(self):
        """Initialize game phases and steps from DSL."""
        pass
    def setup_game(self):
        """Custom game setup logic from DSL."""
        super().setup_game()  # Call engine base setup
        # DSL Custom Logic
        pass

    # ------------------------------------------
    def get_alive_players(self, roles: Optional[List] = None) -> List[str]:
        """Get names of alive players, optionally filtered by roles."""
        return [name for name, p in self.players.items() 
                    if p.is_alive and (roles is None or p.role in [getattr(r, 'value', r) for r in roles])]

if __name__ == "__main__":
    # Simple test execution
    players_data = [{'name': f'Player{i}'} for i in range(6)]
    game_instance = SimpleGame(players_data)
    game_instance.setup_game()
    print(f"Game '{game_instance.name}' initialized with {len(game_instance.phases)} phases.")
