"""
Generated by Wolf DSL Translator
Game: WerewolfGame
"""

import random
import sys
import json
import time
from pathlib import Path
from enum import Enum
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any, Callable, Union

try:
    from engine import ActionContext, GameAction, GameStep, GamePhase, Role, DeathReason, GameEngine
except ImportError:
    from .engine import ActionContext, GameAction, GameStep, GamePhase, Role, DeathReason, GameEngine

class NightStartAction(GameAction):
    def description(self)->str: return "Night start"
    def execute(self, context:ActionContext)->Any: return context.game.action_night_start(context.target)

class GuardActionAction(GameAction):
    def description(self)->str: return "Guard action"
    def execute(self, context:ActionContext)->Any: return context.game.action_guard_action(context.target)

class WerewolfNightActionAction(GameAction):
    def description(self)->str: return "Werewolf night action"
    def execute(self, context:ActionContext)->Any: return context.game.action_werewolf_night_action(context.target)

class SeerActionAction(GameAction):
    def description(self)->str: return "Seer action"
    def execute(self, context:ActionContext)->Any: return context.game.action_seer_action(context.target)

class WitchActionAction(GameAction):
    def description(self)->str: return "Witch action"
    def execute(self, context:ActionContext)->Any: return context.game.action_witch_action(context.target)

class DayStartAction(GameAction):
    def description(self)->str: return "Day start"
    def execute(self, context:ActionContext)->Any: return context.game.action_day_start(context.target)

class DayDiscussionAction(GameAction):
    def description(self)->str: return "Day discussion"
    def execute(self, context:ActionContext)->Any: return context.game.action_day_discussion(context.target)

class DayVoteAction(GameAction):
    def description(self)->str: return "Day vote"
    def execute(self, context:ActionContext)->Any: return context.game.action_day_vote(context.target)

class WerewolfGame(GameEngine):
    """WerewolfGame implementation."""

    def __init__(self, players_data: List[Dict[str, Any]]):
        super().__init__(players_data)
        self.day_number = 0
        self.killed_player = ""
        self.last_guarded = ""
        self.player_count = 0
        self.witch_poison_used = False
        self.witch_save_used = False
        self._init_phases()

    def _init_phases(self):
        Night = GamePhase("Night")
        Night.add_step(GameStep("入夜初始化", [Role.ALL], NightStartAction()))
        Night.add_step(GameStep("守卫守护", [Role.GUARD], GuardActionAction()))
        Night.add_step(GameStep("狼人行动", [Role.WEREWOLF], WerewolfNightActionAction()))
        Night.add_step(GameStep("预言家查验", [Role.SEER], SeerActionAction()))
        Night.add_step(GameStep("女巫用药", [Role.WITCH], WitchActionAction()))
        self.phases.append(Night)
        Day = GamePhase("Day")
        Day.add_step(GameStep("天亮结算", [Role.ALL], DayStartAction()))
        Day.add_step(GameStep("白天讨论", [Role.ALL], DayDiscussionAction()))
        Day.add_step(GameStep("白天投票", [Role.ALL], DayVoteAction()))
        self.phases.append(Day)

    def setup_game(self):
        print("#@ 狼人杀游戏初始化开始")
        self.logger.log_event("#@ 狼人杀游戏初始化开始", self.all_player_names)
        self.player_count =len(self.all_player_names)
        print(f"#@ 本局玩家人数: {self.player_count}")
        self.logger.log_event(f"#@ 本局玩家人数: {self.player_count}", self.all_player_names)
        self.role_config = {
        }
        if self.player_count == 6:
            self.role_config = {
                Role.WEREWOLF.value : 2,
                Role.VILLAGER.value : 2,
                Role.SEER.value : 1,
                Role.WITCH.value : 1,
            }
        else:
            self.role_config = {
                Role.WEREWOLF.value : max(1, self.player_count),
                Role.SEER.value : 1,
                Role.WITCH.value : 1,
                Role.HUNTER.value : 1,
                Role.GUARD.value : 1,
                Role.VILLAGER.value: 0,
            }
            self.role_config[Role.VILLAGER.value] = self.player_count - sum(self.role_config.values())
        role_str =[]
        for role, count in self.role_config.items():
            role_str.append(f"{role.capitalize()} {count}人")
        print(f"#@ 本局游戏角色配置: {', '.join(role_str)}")
        self.logger.log_event(f"#@ 本局游戏角色配置: {', '.join(role_str)}", self.all_player_names)
        print("#@ 角色分配完成, 正在分发身份牌...")
        self.logger.log_event("#@ 角色分配完成, 正在分发身份牌...", self.all_player_names)
        for name in self.all_player_names:
            role = ""
            print(f"\n{name}, 你的身份是: {role.capitalize()}")
            self.logger.log_event(f"\n{name}, 你的身份是: {role.capitalize()}", self.all_player_names)
            if role == Role.WEREWOLF.value:
                teammates =[]
                if len(teammates) > 0:
                    print(f"你的狼人同伴是: {', '.join(teammates)}")
                    self.logger.log_event(f"你的狼人同伴是: {', '.join(teammates)}", self.all_player_names)
                else:
                    print("你是唯一的狼人")
                    self.logger.log_event("你是唯一的狼人", self.all_player_names)
        print("#: 游戏开始.天黑, 请闭眼.")
        self.logger.log_event("#: 游戏开始.天黑, 请闭眼.", self.all_player_names)

    def action_night_start(self, target=None):
        self.day_number = self.day_number + 1
        print(f"#@ 第 {self.day_number} 天夜晚降临")
        self.logger.log_event(f"#@ 第 {self.day_number} 天夜晚降临", self.all_player_names)
        self.killed_player = ""
        print("#@ 入夜初始化完成，重置死亡标记与守护状态")
        self.logger.log_event("#@ 入夜初始化完成，重置死亡标记与守护状态", self.all_player_names)

    def action_guard_action(self, target=None):
        print("#@ 守卫请睁眼")
        self.logger.log_event("#@ 守卫请睁眼", self.all_player_names)
        self.prompt = "守卫, 请选择你要守护的玩家(不能连续两晚守护同一个人): "
        print(self.prompt)
        self.logger.log_event(self.prompt, self.all_player_names)
        alive_players = self._get_alive_players(None)
        valid_targets =[]
        for p in alive_players:
            if p != self.last_guarded:
                valid_targets.append(p)
        target = ""
        print(f"#@ 守卫选择守护: {target}")
        self.logger.log_event(f"#@ 守卫选择守护: {target}", self.all_player_names)
        self.last_guarded = target
        print("#@ 守卫请闭眼")
        self.logger.log_event("#@ 守卫请闭眼", self.all_player_names)
        print("#@ 守卫行动完成，已标记守护目标")
        self.logger.log_event("#@ 守卫行动完成，已标记守护目标", self.all_player_names)

    def action_werewolf_night_action(self, target=None):
        werewolves = self._get_alive_players([Role.WEREWOLF.value])
        if len(werewolves) == 0:
            return
        print("#@ 狼人请睁眼")
        self.logger.log_event("#@ 狼人请睁眼", self.all_player_names)
        print(f"#@ 现在的狼人有: {', '.join(werewolves)}")
        self.logger.log_event(f"#@ 现在的狼人有: {', '.join(werewolves)}", self.all_player_names)
        if len(werewolves) == 1:
            print("#@ 独狼无需讨论，直接进入投票阶段")
            self.logger.log_event("#@ 独狼无需讨论，直接进入投票阶段", self.all_player_names)
        else:
            print("#@ 狼人请开始讨论")
            self.logger.log_event("#@ 狼人请开始讨论", self.all_player_names)
            print("#@ 请轮流发言, 输入 '0' 表示准备好投票")
            self.logger.log_event("#@ 请轮流发言, 输入 '0' 表示准备好投票", self.all_player_names)
            self.discussion_rounds = 0
            self.max_discussion_rounds = 5
            self.ready_to_vote = False
            while  not  self.ready_to_vote  and  self.discussion_rounds < self.max_discussion_rounds:
                self.discussion_rounds = self.discussion_rounds + 1
                print(f"#@ 讨论轮次: {self.discussion_rounds}")
                self.logger.log_event(f"#@ 讨论轮次: {self.discussion_rounds}", self.all_player_names)
                self.ready_to_vote = True
        print("#@ 狼人请投票")
        self.logger.log_event("#@ 狼人请投票", self.all_player_names)
        alive_players = self._get_alive_players(None)
        self.kill_target = ""
        self.killed_player = self.kill_target
        print(f"#@ 狼人达成一致, 选择了击杀 {self.killed_player}")
        self.logger.log_event(f"#@ 狼人达成一致, 选择了击杀 {self.killed_player}", self.all_player_names)
        print("#@ 狼人请闭眼")
        self.logger.log_event("#@ 狼人请闭眼", self.all_player_names)

    def action_seer_action(self, target=None):
        print("#@ 预言家请睁眼")
        self.logger.log_event("#@ 预言家请睁眼", self.all_player_names)
        self.prompt = "预言家, 请选择要查验的玩家: "
        print(self.prompt)
        self.logger.log_event(self.prompt, self.all_player_names)
        alive_players = self._get_alive_players(None)
        target = ""
        role = ""
        identity = "狼人" if(role == Role.WEREWOLF.value) else "好人"
        print(f"#@ 查验结果: {target} 的身份是 {identity}")
        self.logger.log_event(f"#@ 查验结果: {target} 的身份是 {identity}", self.all_player_names)
        print("#@ 预言家请闭眼")
        self.logger.log_event("#@ 预言家请闭眼", self.all_player_names)

    def action_witch_action(self, target=None):
        print("#@ 女巫请睁眼")
        self.logger.log_event("#@ 女巫请睁眼", self.all_player_names)
        self.is_guarded = False
        if self.killed_player != "":
            if self.is_guarded:
                print(f"#@ 今晚是个平安夜, {self.killed_player} 被守护了")
                self.logger.log_event(f"#@ 今晚是个平安夜, {self.killed_player} 被守护了", self.all_player_names)
            else:
                print(f"#@ 今晚 {self.killed_player} 被杀害了")
                self.logger.log_event(f"#@ 今晚 {self.killed_player} 被杀害了", self.all_player_names)
                if  not  self.witch_save_used:
                    use_save = ""
                    if use_save == "y":
                        self.witch_save_used = True
                        print(f"#@ 你使用解药救了 {self.killed_player}")
                        self.logger.log_event(f"#@ 你使用解药救了 {self.killed_player}", self.all_player_names)
                        self.killed_player = ""
        if  not  self.witch_poison_used:
            use_poison = ""
            if use_poison == "y":
                alive_players = self._get_alive_players(None)
                target = ""
                self.witch_poison_used = True
                print(f"#@ 你使用毒药毒了 {target}")
                self.logger.log_event(f"#@ 你使用毒药毒了 {target}", self.all_player_names)
                if self.killed_player == "":
                    self.killed_player = target
                else:
                    self.handle_death(target, DeathReason.POISONED_BY_WITCH)
        print("#@ 女巫请闭眼")
        self.logger.log_event("#@ 女巫请闭眼", self.all_player_names)

    def action_day_start(self, target=None):
        print("#: 天亮了.")
        self.logger.log_event("#: 天亮了.", self.all_player_names)
        print(f"#@ 现在是第 {self.day_number} 天白天")
        self.logger.log_event(f"#@ 现在是第 {self.day_number} 天白天", self.all_player_names)
        if self.killed_player != "":
            self.handle_death(self.killed_player, DeathReason.KILLED_BY_WEREWOLF)
            role = ""
            if role == Role.HUNTER.value:
                self.handle_hunter_shot(self.killed_player)
        else:
            print("#@ 今晚是平安夜")
            self.logger.log_event("#@ 今晚是平安夜", self.all_player_names)

    def action_day_discussion(self, target=None):
        alive_players = self._get_alive_players(None)
        print(f"#@ 场上存活的玩家: {', '.join(alive_players)}")
        self.logger.log_event(f"#@ 场上存活的玩家: {', '.join(alive_players)}", self.all_player_names)
        for player in alive_players:
            speech = ""
            print(f"#: {player} 发言: {speech}")
            self.logger.log_event(f"#: {player} 发言: {speech}", self.all_player_names)

    def action_day_vote(self, target=None):
        print("#@ 请开始投票")
        self.logger.log_event("#@ 请开始投票", self.all_player_names)
        alive_players = self._get_alive_players(None)
        votes = {
        }
        for player in alive_players:
            votes[player] = 0
        for voter in alive_players:
            target = ""
            votes[target] = votes[target] + 1
            print(f"#: {voter} 投票给 {target}")
            self.logger.log_event(f"#: {voter} 投票给 {target}", self.all_player_names)
        max_votes = 0
        voted_out_players =[]
        for player in alive_players:
            if votes[player] > max_votes:
                max_votes = votes[player]
                voted_out_players =[player]
            elif votes[player] == max_votes:
                voted_out_players.append(player)
        if len(voted_out_players) == 1:
            voted_out = voted_out_players[0]
            self.handle_death(voted_out, DeathReason.VOTED_OUT)
            role = ""
            if role == Role.HUNTER.value:
                self.handle_hunter_shot(voted_out)
        else:
            print("#@ 投票平票, 无人出局")
            self.logger.log_event("#@ 投票平票, 无人出局", self.all_player_names)
        self.check_game_over()

    def get_alive_players(self, roles_filter=None):
        print(f"获取存活玩家列表，过滤角色: {roles_filter}")
        self.logger.log_event(f"获取存活玩家列表，过滤角色: {roles_filter}", self.all_player_names)

    def handle_hunter_shot(self, hunter_name=None):
        print(f"{hunter_name} 是猎人，触发开枪逻辑")
        self.logger.log_event(f"{hunter_name} 是猎人，触发开枪逻辑", self.all_player_names)
        alive_players = self._get_alive_players(None)
        valid_targets =[]
        for p in alive_players:
            if p != hunter_name:
                valid_targets.append(p)
        print(f"猎人可选择带走的玩家: {valid_targets}")
        self.logger.log_event(f"猎人可选择带走的玩家: {valid_targets}", self.all_player_names)

    def check_game_over(self):
        self.alive_werewolves = self._get_alive_players([Role.WEREWOLF.value])
        self.alive_villagers = self._get_alive_players([Role.VILLAGER.value, Role.SEER.value, Role.WITCH.value, Role.HUNTER.value, Role.GUARD.value])
        if len(self.alive_werewolves) == 0:
            print("游戏结束, 好人阵营胜利!")
            self.logger.log_event("游戏结束, 好人阵营胜利!", self.all_player_names)
            self.game_over = True
        elif len(self.alive_werewolves) >=len(self.alive_villagers):
            print("游戏结束, 狼人阵营胜利!")
            self.logger.log_event("游戏结束, 狼人阵营胜利!", self.all_player_names)
            self.game_over = True

if __name__ == "__main__":
    game = WerewolfGame([{'player_name': f'Player{i}'} for i in range(12)])
    try: game.run_game()
    except KeyboardInterrupt: pass
    except Exception as e: print(e); import traceback; traceback.print_exc()
