"""
Generated by Wolf DSL Translator
Game: WerewolfGame
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
import random
import time
from typing import List, Dict, Optional, Any, Callable
import sys
import json
import os
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(BASE))

try:
    from src.Logger import GameLogger
    from src.services.players import Player
except ImportError:
    # Mock if not found
    class GameLogger:
        def __init__(self, name, players): pass
        def log_event(self, msg, targets=None): pass
    class Player:
        def __init__(self, name, role, config, prompts, logger):
            self.name = name
            self.role = role
            self.is_alive = True
            self.config = config
            self.prompts = prompts
            self.logger = logger

# ==========================================
# Core Engine Structures
# ==========================================

from src.engine import ActionContext, GameAction, GameStep, GamePhase

class Role(Enum):
    ALL = "all"
    WEREWOLF = "werewolf"
    VILLAGER = "villager"
    SEER = "seer"
    WITCH = "witch"
    HUNTER = "hunter"
    GUARD = "guard"

class DeathReason(Enum):
    KILLED_BY_WEREWOLF = "在夜晚被杀害"
    POISONED_BY_WITCH = "被女巫毒杀"
    VOTED_OUT = "被投票出局"
    SHOT_BY_HUNTER = "被猎人带走"

# ==========================================
# Action Classes
# ==========================================

class Night_startAction(GameAction):
    """Action class for DSL action: night_start"""
    def description(self) -> str:
        return "night_start"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_night_start(target)

class Guard_actionAction(GameAction):
    """Action class for DSL action: guard_action"""
    def description(self) -> str:
        return "guard_action"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_guard_action(target)

class Werewolf_night_actionAction(GameAction):
    """Action class for DSL action: werewolf_night_action"""
    def description(self) -> str:
        return "werewolf_night_action"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_werewolf_night_action(target)

class Seer_actionAction(GameAction):
    """Action class for DSL action: seer_action"""
    def description(self) -> str:
        return "seer_action"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_seer_action(target)

class Witch_actionAction(GameAction):
    """Action class for DSL action: witch_action"""
    def description(self) -> str:
        return "witch_action"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_witch_action(target)

class Day_startAction(GameAction):
    """Action class for DSL action: day_start"""
    def description(self) -> str:
        return "day_start"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_day_start(target)

class Day_discussionAction(GameAction):
    """Action class for DSL action: day_discussion"""
    def description(self) -> str:
        return "day_discussion"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_day_discussion(target)

class Day_voteAction(GameAction):
    """Action class for DSL action: day_vote"""
    def description(self) -> str:
        return "day_vote"

    def execute(self, context: ActionContext) -> Any:
        game = context.game
        target = context.target
        game.action_day_vote(target)

# ==========================================
# Main Game Class
# ==========================================

class WerewolfGame:
    """WerewolfGame implementation generated from DSL."""

    def __init__(self, players: List[Dict[str, str]]):
        self.players: Dict[str, Player] = {}
        self.roles: Dict[str, str] = {}
        self.all_player_names: List[str] = [p.get("player_name", "") for p in players]
        self.phases: List[GamePhase] = []
        self.logger = GameLogger("werewolf", players)
        self.game_over = False
        # DSL Global Variables
        self.day_number = 0
        self.killed_player = ""
        self.last_guarded = ""
        self.player_count = 0
        self.witch_poison_used = False
        self.witch_save_used = False

        self._init_phases()

    def _init_phases(self):
        """Initialize phases and steps from DSL."""
        Night = GamePhase("Night")
        Night.add_step(GameStep("入夜初始化", [Role.ALL], Night_startAction()))
        Night.add_step(GameStep("守卫守护", [Role.GUARD], Guard_actionAction()))
        Night.add_step(GameStep("狼人行动", [Role.WEREWOLF], Werewolf_night_actionAction()))
        Night.add_step(GameStep("预言家查验", [Role.SEER], Seer_actionAction()))
        Night.add_step(GameStep("女巫用药", [Role.WITCH], Witch_actionAction()))
        self.phases.append(Night)

        Day = GamePhase("Day")
        Day.add_step(GameStep("天亮结算", [Role.ALL], Day_startAction()))
        Day.add_step(GameStep("白天讨论", [Role.ALL], Day_discussionAction()))
        Day.add_step(GameStep("白天投票", [Role.ALL], Day_voteAction()))
        self.phases.append(Day)

    def setup_game(self):
        """Custom game setup logic from DSL."""
        # DSL setup block
        print("#@ 狼人杀游戏初始化开始")
        self.player_count =len(self.all_player_names)
        print(f"#@ 本局玩家人数: {self.player_count}")
        self.role_config = {
        }
        if self.player_count == 6:
            self.role_config = {
                "werewolf" : 2,
                "villager" : 2,
                "seer" : 1,
                "witch" : 1,
            }
        else:
            self.role_config = {
                "werewolf" : max(1, self.player_count),
                "seer" : 1,
                "witch" : 1,
                "hunter" : 1,
                "guard" : 1,
                "villager": 0,
            }
            self.role_config["villager"] = self.player_count - sum(self.role_config.values())
        role_str =[]
        for role, count in self.role_config.items():
            role_str.append(role.capitalize() + " " + count + "人")
        print(f"#@ 本局游戏角色配置: {', '.join(role_str)}")
        print("#@ 角色分配完成, 正在分发身份牌...")
        for name in self.all_player_names:
            role = ""
            print(f"\n{name}, 你的身份是: {role.capitalize()}")
            if role == "werewolf":
                teammates =[]
                if len(teammates) > 0:
                    print(f"你的狼人同伴是: {', '.join(teammates)}")
                else:
                    print("你是唯一的狼人")
        print("#: 游戏开始.天黑, 请闭眼.")

        # Generated Player Initialization
        role_list = []
        if hasattr(self, 'role_config') and self.role_config:
            for role, count in self.role_config.items():
                for _ in range(count):
                    role_list.append(role)
        else:
            # Fallback if role_config is not defined or empty
            role_list = ["villager"] * len(self.all_player_names)
        random.shuffle(role_list)

        for i, name in enumerate(self.all_player_names):
            role_str = role_list[i] if i < len(role_list) else "villager"
            player = Player(name, role_str, {}, {}, self.logger)
            self.players[name] = player
            self.roles[name] = role_str

    def get_alive_players(self, roles_filter=None):
        alive = []
        for p in self.players.values():
            if p.is_alive:
                if roles_filter is None or p.role in roles_filter:
                    alive.append(p.name)
        return alive

    def handle_death(self, player_name: str, reason: DeathReason):
        if player_name in self.players:
            self.players[player_name].is_alive = False
        print(f"#! {player_name} {reason.value}")

    def _get_player_by_role(self, role_str: str):
        for p in self.players.values():
            if p.role == role_str and p.is_alive:
                return p
        return None

    def run_game(self):
        self.setup_game()
        while not self.game_over:
            for phase in self.phases:
                if self.game_over: break
                for step in phase.steps:
                    if self.game_over: break
                    if step.action is not None:
                        context = ActionContext(game=self)
                        step.action.execute(context)
                    else:
                        print(f"DEBUG: Skipping step {step.name} (no action defined)")
        print("Game Over.")

    def action_night_start(self, target=None):
        self.day_number = self.day_number + 1
        print(f"#@ 第 {self.day_number} 天夜晚降临")
        self.killed_player = ""
        print("#@ 入夜初始化完成，重置死亡标记与守护状态")

    def action_guard_action(self, target=None):
        print("#@ 守卫请睁眼")
        self.prompt = "守卫, 请选择你要守护的玩家(不能连续两晚守护同一个人): "
        print(self.prompt)
        alive_players = self.get_alive_players()
        valid_targets =[]
        for p in alive_players:
            if p != self.last_guarded:
                valid_targets.append(p)
        self.target = ""
        print(f"#@ 守卫选择守护: {self.target}")
        self.last_guarded = self.target
        print("#@ 守卫请闭眼")
        print("#@ 守卫行动完成，已标记守护目标")

    def action_werewolf_night_action(self, target=None):
        werewolves = self.get_alive_players(["werewolf"])
        if len(werewolves) == 0:
            return
        print("#@ 狼人请睁眼")
        print(f"#@ 现在的狼人有: {', '.join(werewolves)}")
        if len(werewolves) == 1:
            print("#@ 独狼无需讨论，直接进入投票阶段")
        else:
            print("#@ 狼人请开始讨论")
            print("#@ 请轮流发言, 输入 '0' 表示准备好投票")
            self.discussion_rounds = 0
            self.max_discussion_rounds = 5
            self.ready_to_vote = False
            while  not  self.ready_to_vote  and  self.discussion_rounds < self.max_discussion_rounds:
                self.discussion_rounds = self.discussion_rounds + 1
                print(f"#@ 讨论轮次: {self.discussion_rounds}")
                self.ready_to_vote = True
        print("#@ 狼人请投票")
        alive_players = self.get_alive_players()
        self.kill_target = ""
        self.killed_player = self.kill_target
        print(f"#@ 狼人达成一致, 选择了击杀 {self.killed_player}")
        print("#@ 狼人请闭眼")

    def action_seer_action(self, target=None):
        print("#@ 预言家请睁眼")
        self.prompt = "预言家, 请选择要查验的玩家: "
        print(self.prompt)
        alive_players = self.get_alive_players()
        self.target = ""
        role = ""
        self.identity = "狼人" if(role == "werewolf") else "好人"
        print(f"#@ 查验结果: {self.target} 的身份是 {self.identity}")
        print("#@ 预言家请闭眼")

    def action_witch_action(self, target=None):
        print("#@ 女巫请睁眼")
        self.is_guarded = False
        if self.killed_player != "":
            if self.is_guarded:
                print(f"#@ 今晚是个平安夜, {self.killed_player} 被守护了")
            else:
                print(f"#@ 今晚 {self.killed_player} 被杀害了")
                if  not  self.witch_save_used:
                    self.use_save = ""
                    if self.use_save == "y":
                        self.witch_save_used = True
                        print(f"#@ 你使用解药救了 {self.killed_player}")
                        self.killed_player = ""
        if  not  self.witch_poison_used:
            self.use_poison = ""
            if self.use_poison == "y":
                alive_players = self.get_alive_players()
                self.target = ""
                self.witch_poison_used = True
                print(f"#@ 你使用毒药毒了 {self.target}")
                if self.killed_player == "":
                    self.killed_player = self.target
                else:
                    print(f"#! {self.target} 死了, 原因是被女巫毒杀")
        print("#@ 女巫请闭眼")

    def action_day_start(self, target=None):
        print("#: 天亮了.")
        print(f"#@ 现在是第 {self.day_number} 天白天")
        if self.killed_player != "":
            print(f"#! {self.killed_player} 死了, 原因是在夜晚被杀害")
            role = ""
            if role == "hunter":
                self.handle_hunter_shot(self.killed_player)
        else:
            print("#@ 今晚是平安夜")

    def action_day_discussion(self, target=None):
        alive_players = self.get_alive_players()
        print(f"#@ 场上存活的玩家: {', '.join(alive_players)}")
        for player in alive_players:
            self.speech = ""
            print(f"#: {player} 发言: {self.speech}")

    def action_day_vote(self, target=None):
        print("#@ 请开始投票")
        alive_players = self.get_alive_players()
        self.votes = {
        }
        for player in alive_players:
            self.votes[player] = 0
        for voter in alive_players:
            self.target = ""
            self.votes[self.target] = self.votes[self.target] + 1
            print(f"#: {voter} 投票给 {self.target}")
        self.max_votes = 0
        voted_out_players =[]
        for player in alive_players:
            if self.votes[player] > self.max_votes:
                self.max_votes = self.votes[player]
                voted_out_players =[player]
            elif self.votes[player] == self.max_votes:
                voted_out_players.append(player)
        if len(voted_out_players) == 1:
            self.voted_out = voted_out_players[0]
            print(f"#! 投票结果: {self.voted_out} 被投票出局")
            role = ""
            if role == "hunter":
                self.handle_hunter_shot(self.voted_out)
        else:
            print("#@ 投票平票, 无人出局")
        self.check_game_over()

    def handle_hunter_shot(self, hunter_name=None):
        print(f"{hunter_name} 是猎人，触发开枪逻辑")
        alive_players = self.get_alive_players()
        valid_targets =[]
        for p in alive_players:
            if p != hunter_name:
                valid_targets.append(p)
        print(f"猎人可选择带走的玩家: {valid_targets}")

    def check_game_over(self):
        alive_werewolves = self.get_alive_players(["werewolf"])
        alive_villagers = self.get_alive_players(["villager", "seer", "witch", "hunter", "guard"])
        if len(alive_werewolves) == 0:
            print("游戏结束, 好人阵营胜利!")
            self.game_over = True
        elif len(alive_werewolves) >=len(alive_villagers):
            print("游戏结束, 狼人阵营胜利!")
            self.game_over = True

if __name__ == "__main__":
    # Simple test execution
    players_data = [{'player_name': f'Player{i}'} for i in range(12)]
    game = WerewolfGame(players_data)
    try:
        game.run_game()
    except KeyboardInterrupt:
        print("\nGame terminated by user.")
    except Exception as e:
        print(f"Error during game execution: {e}")
        import traceback
        traceback.print_exc()
