"""
Generated by Wolf DSL Translator
Game: WerewolfSimple
"""

import random
import sys
import json
import time
from pathlib import Path
from enum import Enum
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any, Callable, Union

try:
    from engine import ActionContext, GameAction, GameStep, GamePhase, Role, DeathReason, GameEngine
except ImportError:
    from .engine import ActionContext, GameAction, GameStep, GamePhase, Role, DeathReason, GameEngine

class KillAction(GameAction):
    def description(self)->str: return "Kill"
    def execute(self, context:ActionContext)->Any: return context.game.action_kill(context.target)

class VoteAction(GameAction):
    def description(self)->str: return "Vote"
    def execute(self, context:ActionContext)->Any: return context.game.action_vote(context.target)

class WerewolfSimple(GameEngine):
    """WerewolfSimple implementation."""

    def __init__(self, players_data: List[Dict[str, Any]]):
        super().__init__(players_data)
        self.day_count = 1
        self._init_phases()

    def _init_phases(self):
        night = GamePhase("night")
        night.add_step(GameStep("kill", [Role.WEREWOLF], KillAction()))
        self.phases.append(night)
        day = GamePhase("day")
        day.add_step(GameStep("vote", [Role.WEREWOLF, Role.VILLAGER], VoteAction()))
        self.phases.append(day)

    def setup_game(self):
        print("狼人杀简化版启动。")
        self.logger.log_event("狼人杀简化版启动。", self.all_player_names)
        self.day_count = 1
        self.game_over = False

    def action_kill(self, target=None):
        print(f"狼人杀害了: {target}")
        self.logger.log_event(f"狼人杀害了: {target}", self.all_player_names)

    def action_vote(self, target=None):
        print(f"投票给了: {target}")
        self.logger.log_event(f"投票给了: {target}", self.all_player_names)

if __name__ == "__main__":
    game = WerewolfSimple([{'player_name': f'Player{i}'} for i in range(12)])
    try: game.run_game()
    except KeyboardInterrupt: pass
    except Exception as e: print(e); import traceback; traceback.print_exc()
