"""
Generated by Wolf DSL Translator
Game: WerewolfGame
"""

import random
import time
from pathlib import Path
from typing import List, Dict, Optional

# Engine Imports
from game.engine import Game, GamePhase, GameStep, GameAction
from game.models import Role, DeathReason
from game.player import Player


# ==========================================
# Action Classes
# ==========================================

class KillAction(GameAction):
    """Action class for DSL action: kill"""
    def execute(self, game, player, target=None):
        game.action_kill(target)

class VoteAction(GameAction):
    """Action class for DSL action: vote"""
    def execute(self, game, player, target=None):
        game.action_vote(target)

class CheckAction(GameAction):
    """Action class for DSL action: check"""
    def execute(self, game, player, target=None):
        game.action_check(target)

# ==========================================
# Main Game Class
# ==========================================

class WerewolfGame(Game):
    """WerewolfGame implementation generated from DSL."""

    def __init__(self, players: List[Dict[str, str]], event_emitter=None, input_handler=None):
        super().__init__("WerewolfGame", players, event_emitter, input_handler)

        # DSL Global Variables
        self.day_count = 1
        self.game_over = False
        self.night_count = 0

        self._init_phases()

    def _init_phases(self):
        """Initialize game phases and steps from DSL."""
        night_phase = GamePhase("night_phase")
        night_phase.add_step(GameStep("werewolf_action", [Role.werewolf], KillAction()))
        night_phase.add_step(GameStep("seer_action", [Role.seer], CheckAction()))
        self.phases.append(night_phase)

        day_phase = GamePhase("day_phase")
        day_phase.add_step(GameStep("discussion", [Role.werewolf, Role.villager, Role.seer, Role.witch], None))
        day_phase.add_step(GameStep("voting", [Role.werewolf, Role.villager, Role.seer, Role.witch], VoteAction()))
        self.phases.append(day_phase)

    def setup_game(self):
        """Custom game setup logic from DSL."""
        super().setup_game()  # Call engine base setup
        # DSL Custom Logic
        print("Werewolf game started!")
        test_var = 10
        if test_var > 5:
            print("test_var is greater than 5")
        for i in range(3):
            print(f"Loop iteration:  {i}")
        print("Roles assigned")

    def action_kill(self, target):
        print(f"Werewolf selected target:  {target}")

    def action_vote(self, target):
        print(f"Villager voted for:  {target}")

    def action_check(self, target):
        print(f"Seer checked:  {target}")

    # ------------------------------------------
    def get_alive_players(self, roles: Optional[List] = None) -> List[str]:
        """Get names of alive players, optionally filtered by roles."""
        return [name for name, p in self.players.items() 
                    if p.is_alive and (roles is None or p.role in [getattr(r, 'value', r) for r in roles])]

if __name__ == "__main__":
    # Simple test execution
    players_data = [{'name': f'Player{i}'} for i in range(6)]
    game_instance = WerewolfGame(players_data)
    game_instance.setup_game()
    print(f"Game '{game_instance.name}' initialized with {len(game_instance.phases)} phases.")
